id: PB38C9952
initial_creation_type: ocr
source_metadata:
  volumes:
    918a8bfe980b48f093797aa45c70b28a:
      base_file: v067.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་བཟང་པོ་སྤྱོད་པའི་སྨོན་ལམ་གྱི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
